More Advanced Matching Algorithm
googleinterns/ResumeBuddy pull request #33
Opened 2020-07-09 21:02 UTC by AniMachaidze

Add more advanced matching algorithm and test cases.

Algorithm is based on points system which describes similarity between reviewee-reviewer pair. Possible pairs are sorted in decreasing order based on their _matchpoints_. Going through the list, available pairs with biggest _matchpoints_ are matched. People with 0 _matchpoints_ are not matched unless on of them has been waiting for a match for more than 3 days.

2020-07-10 19:08 UTC, oydang requested changes
Awesome job! Just some stylistic nits.

2020-07-10 19:08 UTC, oydang commented on resume-buddy/src/main/java/com/google/sps/Match.java
> +public class Match extends HttpServlet {
Nit: rename this class to MatchServlet and move it to the /servlets folder.

2020-07-10 19:08 UTC, oydang commented on resume-buddy/src/main/java/com/google/sps/Match.java
> +          matchPoint += 3;
The points system is a great idea!

You can make these points constants at the top of this class. Eg.
```
private static final int CAREER_POINTS = 3;
private static final int SCHOOL_POINTS = 2;
...
```

2020-07-10 19:08 UTC, oydang commented on resume-buddy/src/main/java/com/google/sps/Match.java
> +        if (timeSinceSubmitReviewee < 3 && timeSinceSubmitReviewer < 3) {
The 3 days should be a constant as well.

`private static final int DAYS_TO_WAIT_UNTIL_TRY_MATCH = 3` (you can come up with a better name than mine, haha).

2020-07-10 19:08 UTC, oydang commented on resume-buddy/src/main/java/com/google/sps/Match.java
> +  /** Comparator that compares based on the point value and sorts list from bigest to smallest */
Nit: biggest

2020-07-13 12:51 UTC, oydang commented
Please resolve merge conflicts first, then I'll be able to review the most up-to-date code!

2020-07-13 14:25 UTC, astrelni submitted a review, later dismissed

2020-07-13 14:25 UTC, astrelni commented on resume-buddy/src/main/java/com/google/sps/Match.java
> +      for (Entity reviewer : reviewers) {
Should probably add a check at the start of the inner loop for whether reviewee and reviewer are the same person.

2020-07-13 14:26 UTC, oydang requested changes

2020-07-13 14:26 UTC, oydang commented on resume-buddy/src/main/java/com/google/sps/Match.java
> +import java.util.*;
Google style guide: Avoid wildcard imports. https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

2020-07-13 14:26 UTC, oydang commented on resume-buddy/src/main/java/com/google/sps/data/ReviewStatus.java
> +public enum ReviewStatus {
A quick comment explaining how this enum is used would be helpful.

2020-07-13 14:26 UTC, oydang commented on resume-buddy/src/main/java/com/google/sps/servlets/RevieweeDataServlet.java
> +    revieweeEntity.setProperty("submitdate", new Date());
This should be `submit-date` instead of `submitdate`.

2020-07-13 17:28 UTC, oydang approved these changes

2020-07-13 19:12 UTC, merged