Use BlobKey as a PDF ID
googleinterns/ResumeBuddy pull request #81
Opened 2020-07-22 20:03 UTC by shayla11

This code, is editing the existing adobe dc view to add a unique pdf ID inorder to utilize several annotation API's (enableAnnotationAPI & includePDFAnnotations). We are doing this by making a response header that will hold the blobkey. 

I also created another blobkey that holds the reviewee's email, so now that file name can be unique for each pdf. Right now we are only using the email, but this can be changed to a different naming convention.

2020-07-22 20:44 UTC, oydang requested changes
Nice! How did it work out? Is the annotations toolbar displayed and does it show the save button?

2020-07-22 20:44 UTC, oydang commented on resume-buddy/src/main/webapp/scripts/resume-review-script.js
> +        const resumeFileName = response.headers.get('newResumeFileName');
Nit: These are indented 2 extra spaces

2020-07-22 20:44 UTC, oydang commented on resume-buddy/src/main/webapp/scripts/resume-review-script.js
> +  //"embedMode": "IN_LINE",
If want to leave this commented out, might as well delete it.

2020-07-22 20:44 UTC, oydang commented on resume-buddy/src/main/webapp/scripts/resume-review-script.js
>          clientId: "",
JavaScript empty string should be `''` instead of `""`

2020-07-22 20:44 UTC, oydang commented on resume-buddy/src/main/webapp/scripts/resume-review-script.js
>          divId: "adobe-dc-view"
Use single quotes for JS strings: `'adobe-dv-view'`

2020-07-22 20:44 UTC, oydang commented on resume-buddy/src/main/webapp/scripts/resume-review-script.js
> +          fileName: resumeFileName + "Resume.pdf",
`'Resume.pdf'` instead of `"Resume.pdf"`

2020-07-22 21:35 UTC, shayla11 commented
Yes! Sorry, I meant to explain what happened originally in a new comment. But yes the code works! The save button appears once you have edited the file. After you click the save button, the file automatically downloads the pdf with the new annotations.

 I had to disable the `embedMode: "IN_LINE"` attribute because It would not show the tool bar of the annotation tools. I'm not sure what the default view is, but whatever it is, it allows the tools to be shown.

@oydang

2020-07-23 15:30 UTC, oydang approved these changes

2020-07-23 16:00 UTC, merged